# Generated by Django 5.0 on 2024-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=9000, max_digits=8),
            preserve_default=False,
        ),
    ]
