# Generated by Django 5.0 on 2024-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_enquiry', '0002_book_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
